[build]
  publish = "."
  command = "chmod +x build.sh && ./build.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python -m http.server 8000"
  targetPort = 8000
  framework = "#static"